#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Malline
  class Parser < Racc::Parser


require_relative 'handler'

def initialize lexer, handler=Handler.new
  @lexer   = lexer
  @handler = handler
  super()
end

def next_token
  token, string, start_line, end_line = @lexer.next_token
  @handler.token_line = [start_line, end_line]
  [token, string] if token
end

def parse
  do_parse
  @handler
end
##### State transition tables begin ###

racc_action_table = [
     7,     5,     5,     6,     6,     9,    11,    10,    12,    13,
    14,    15 ]

racc_action_check = [
     1,     0,     1,     0,     1,     5,     5,     5,     7,    10,
    11,    13 ]

racc_action_pointer = [
    -1,     0,   nil,   nil,   nil,     2,   nil,     8,   nil,   nil,
     5,     7,   nil,     8,   nil,   nil ]

racc_action_default = [
    -9,    -9,    -2,    -3,    -4,    -9,    -8,    -9,    -1,    -5,
    -9,    -9,    16,    -9,    -7,    -6 ]

racc_goto_table = [
     2,     8,     1 ]

racc_goto_check = [
     2,     2,     1 ]

racc_goto_pointer = [
   nil,     2,     0,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 7, :_reduce_none,
  1, 7, :_reduce_none,
  1, 8, :_reduce_none,
  1, 8, :_reduce_none,
  2, 9, :_reduce_none,
  4, 9, :_reduce_6,
  3, 9, :_reduce_7,
  1, 10, :_reduce_8 ]

racc_reduce_n = 9

racc_shift_n = 16

racc_token_table = {
  false => 0,
  :error => 1,
  :START_CODE => 2,
  :END_CODE => 3,
  :DATA => 4,
  :CMD => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "START_CODE",
  "END_CODE",
  "DATA",
  "CMD",
  "$start",
  "values",
  "value",
  "code_block",
  "data" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 @handler.code(val[2], val[1].to_sym) 
    result
end

def _reduce_7(val, _values, result)
 @handler.code val[1] 
    result
end

def _reduce_8(val, _values, result)
 @handler.data val.first 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Malline
